### PR TITLE
Add formula for gr-iio

### PR DESCRIPTION
**Pull request by rgov**
This is a formula to install `gr-iio`.

It requires this change to Homebrew for the `gnuradio` formula: https://github.com/Homebrew/homebrew-core/pull/65437

The formula is `HEAD`-only because there is no release that builds with GNU Radio 3.8, which is what Homebrew offers. There is a patch needed to fix a compilation error that I cherry-pick from `master` because it has not yet landed in `upgrade-3.8` yet.

Normally, a Homebrew formula should declares all of its Python package dependencies as `resource` sections to be installed by `pip`, as the mainline `gr-osmosdr` formula does. However it doesn't look to me like there are any.

There are two minor issues with the dependencies:

1. [This wiki page](https://wiki.analog.com/resources/tools-software/linux-software/gnuradio#gnu_radio_38) says that building it requires `liborc-dev` on Linux, so I added the `orc` dependency as well, but I can't figure out if it is actually used?

2. CMake seems to fail to detect MPIR but we build successfully anyway, so I marked it optional. This is something that probably needs to be fixed in `gr-iio`'s CMake configuration. (This needs to be resolved before upstreaming this to `homebrew-core`.)

### CODE REVIEW

**Comment by rgov** [comment]
The pull request has been updated to build `gr-iio` in the CI workflow. All packages are built and tested individually now.

Please see the two bullets above for potential improvements.
